image:
  repository: gcr.io/jenkinsxio/jx-cli
  tag: 3.1.206
  pullPolicy: IfNotPresent

replicaCount: 1

deployment:
  enabled: false

service:
  enabled: false

daemonset:
  enabled: false

job:
  enabled: false

podAnnotations: {}

cronjob:
  enabled: false
  schedule: "* * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid

serviceaccount:
  enabled: false
  customName: ""

role:
  enabled: false
# example:
#  rules:
#  - apiGroups:
#    - jenkins.io
#    resources:
#    - pipelineactivities
#    verbs:
#    - list
#    - delete
#  - apiGroups:
#    - ""
#    resources:
#    - secrets
#    - services
#    verbs:
#    - get
  # rules:
  # - apiGroups:
  #   - jenkins.io
  #   resources:
  #   - environments
  #   verbs:
  #   - list
  #   - delete
  # - apiGroups:
  #   - ""
  #   resources:
  #   - secrets
  #   verbs:
  #   - get
  #   - list
  # - apiGroups:
  #   - apiextensions.k8s.io
  #   resources:
  #   - customresourcedefinitions
  #   verbs:
  #   - create

clusterrole:
  enabled: false
  # rules:
  # - apiGroups:
  #   - apiextensions.k8s.io
  #   resources:
  #   - customresourcedefinitions
  #   verbs:
  #   - get
  # - apiGroups:
  #   - ""
  #   resources:
  #   - namespace
  #   verbs:
  #   - get
  #   - delete
  #   - list
  # - apiGroups:
  #   - ""
  #   resources:
  #   - deployments
  #   verbs:
  #   - get

activeDeadlineSeconds: 300
backoffLimit: 5

# default is Always but for Jobs use Never or OnFailure
restartPolicy: Never

command: ["jx"]
args:
  - "version"

env:
  # lets use JSON output in logs
  JX_LOG_FORMAT: json

  # lets set the logging level
  JX_LOG_LEVEL: info

  # lets mark this pod as being a CI/CD pipeline job so reuse the pipeline git user
  PIPELINE_KIND: dummy

internalPort: 80

probe:
  path: /

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
