
# generated by: jx gitops variables
export APP_NAME="jx-cli"
export BRANCH_NAME="master"
export DOCKERFILE_PATH="Dockerfile"
export DOCKER_REGISTRY="ghcr.io"
export DOCKER_REGISTRY_ORG="jenkins-x"
export MINK_AS="tekton-bot"
export MINK_IMAGE="ghcr.io/jenkins-x/jx-cli:3.1.184"
export PIPELINE_KIND="release"
export REPO_NAME="jx-cli"
export REPO_OWNER="jenkins-x"
export VERSION="3.1.184"
