{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-11T13:50:26Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.0.57

      from: https://github.com/jenkins-x/jx-verify.git
    sha: 28afe4310a88af170681cb5e6a14632327be329c
  - author:
      email: jenkins-x@googlegroups.com
      name: root
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: root
    message: |
      fix: upgrade to version 0.1.5

      from: https://github.com/jenkins-x/jx-gitops.git
    sha: 760707756af832e8874ffb4401ee26cc841eaa01
  gitHttpUrl: https://github.com/jenkins-x/jx-cli
  gitOwner: jenkins-x
  gitRepository: jx-cli
  name: '{{ .Chart.Name }}'
  version: 3.1.241
status: {}
 
{{- end }}
