{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-20T08:03:26Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: root
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: root
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.2.30

      from: https://github.com/jenkins-x/jx-gitops.git
    sha: 1284e19b24ad4964f7b2c63db5f22d641b71e3bf
  - author:
      email: jenkins-x@googlegroups.com
      name: root
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: root
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.2.29

      from: https://github.com/jenkins-x/jx-gitops.git
    sha: 8089bdb5bdbfb0bf29883516df3d3fc8eb040d14
  gitHttpUrl: https://github.com/jenkins-x/jx-cli
  gitOwner: jenkins-x
  gitRepository: jx-cli
  name: '{{ .Chart.Name }}'
  version: 3.1.331
status: {}
 
{{- end }}
