{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-15T05:49:32Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: 27856297+dependabot-preview[bot]@users.noreply.github.com
      name: dependabot-preview[bot]
    branch: master
    committer:
      email: noreply@github.com
      name: GitHub
    message: |-
      chore(deps): bump github.com/spf13/cobra from 1.0.0 to 1.1.3

      Bumps [github.com/spf13/cobra](https://github.com/spf13/cobra) from 1.0.0 to 1.1.3.
      - [Release notes](https://github.com/spf13/cobra/releases)
      - [Changelog](https://github.com/spf13/cobra/blob/master/CHANGELOG.md)
      - [Commits](https://github.com/spf13/cobra/compare/v1.0.0...v1.1.3)

      Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
    sha: 0bf660bab196fed92e08bbaf41a889ddb675ad2b
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.0.35

      from: https://github.com/jenkins-x/jx-test.git
    sha: 9f7c6e8e69ab772e38c66d46fc1048d3b077a2b9
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.0.61

      from: https://github.com/jenkins-x/jx-verify.git
    sha: 379b43d8fe0334bb30520e316a93ae66cd329763
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.0.33

      from: https://github.com/jenkins-x/jx-test.git
    sha: b0213d5e54158f95c834ad074908614d5de6e730
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: lets release the gcp terraform operator image
    sha: 75920311be4bc5555e06937b0a44f9df16194437
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.0.34

      from: https://github.com/jenkins-x/jx-test.git
    sha: 0f522b5c3c2d05dad1efb3443137528123b88ec8
  gitHttpUrl: https://github.com/jenkins-x/jx-cli
  gitOwner: jenkins-x
  gitRepository: jx-cli
  name: '{{ .Chart.Name }}'
  version: 3.1.249
status: {}
 
{{- end }}
