{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-02T12:39:45Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: root
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: root
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.2.13

      from: https://github.com/jenkins-x/jx-gitops.git
    sha: d4b46f44389c46e6abc11fd52d08b8b72a81950e
  - author:
      email: jenkins-x@googlegroups.com
      name: root
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: root
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.2.12

      from: https://github.com/jenkins-x/jx-gitops.git
    sha: cb1b836eb6435c5b56d3775062d0553b2704886e
  gitHttpUrl: https://github.com/jenkins-x/jx-cli
  gitOwner: jenkins-x
  gitRepository: jx-cli
  name: '{{ .Chart.Name }}'
  version: 3.1.290
status: {}
 
{{- end }}
