{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-29T11:10:10Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    message: |
      chore: fix bad updatebot PR
    sha: 8194c7e52854994e33dc22e5b0dd6e23c1aa967d
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    message: |
      chore: fix bad updatebot PR
    sha: 7c917808751de392fab155e685a07339b3baa66e
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    message: |
      chore: fix PRs
    sha: a4ad4b86463b78d1ec89a342697121bb27131ee1
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    message: |
      chore: fix updatebot
    sha: 7588655b2849041c57fdea0558ce2b54780ea4e8
  gitHttpUrl: https://github.com/jenkins-x/jx-cli
  gitOwner: jenkins-x
  gitRepository: jx-cli
  name: '{{ .Chart.Name }}'
  version: 3.1.193
status: {}
 
{{- end }}
