{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-13T12:33:11Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: rawlingsj80@gmail.com
      name: James Rawlings
    branch: master
    committer:
      email: rawlingsj80@gmail.com
      name: James Rawlings
    message: |
      chore: enable multi platform tests for validating plugin mechanism
    sha: 290e4691d35ff12753cca07663de69a951cc565a
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.0.71

      from: https://github.com/jenkins-x/jx-verify.git
    sha: cf105c1e762ad8864f1353b462a9f6b915c7cb06
  gitHttpUrl: https://github.com/jenkins-x/jx-cli
  gitOwner: jenkins-x
  gitRepository: jx-cli
  name: '{{ .Chart.Name }}'
  version: 3.1.307
status: {}
 
{{- end }}
