{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-16T11:28:55Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade jenkins-x/jx-cli to version 0.0.37

      from: https://github.com/jenkins-x/jx-test.git
    sha: ff9ed7bc379055a314041108d925e4f1717328d2
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fix updatebot expression
    sha: a307a60f799420027a344b6e4f3ebfcf8b58aad6
  gitHttpUrl: https://github.com/jenkins-x/jx-cli
  gitOwner: jenkins-x
  gitRepository: jx-cli
  name: '{{ .Chart.Name }}'
  version: 3.1.258
status: {}
 
{{- end }}
